# RSS: Department of State, Travel Advisory Board

## I. Acquisition

In [1]:
import pandas as pd
import requests
import feedparser as fp

In [2]:
url = 'https://travel.state.gov/_res/rss/TAsTWs.xml'
dos_ta = fp.parse(url)
type(dos_ta) #'fp.parse' returns a dictionary

feedparser.FeedParserDict

In [3]:
#We use '.keys()' to find out the dict keys.
dos_ta.keys()

dict_keys(['feed', 'entries', 'bozo', 'headers', 'etag', 'updated', 'updated_parsed', 'href', 'status', 'encoding', 'version', 'namespaces'])

In [4]:
dos_ta_df = pd.DataFrame(dos_ta.entries)

### Saving the data into a local file

In [5]:
dos_ta_df.to_json('./data/dos_ta_raw.json')

## II. Wrangling

In [6]:
dos_score = pd.read_json('./data/dos_ta_raw.json')
dos_score.head()

,dc_identifier,guidislink,id,link,links,published,published_parsed,summary,summary_detail,tags,title,title_detail
0,"BT,advisory",False,http://travel.state.gov/content/travel/en/trav...,http://travel.state.gov/content/travel/en/trav...,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",<p>Exercise normal precautions in Bhutan.&nbsp...,"{'type': 'text/html', 'language': None, 'base'...",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,"{'type': 'text/plain', 'language': None, 'base..."
1,"SG,advisory",False,http://travel.state.gov/content/travel/en/trav...,http://travel.state.gov/content/travel/en/trav...,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",<p>Exercise normal precautions in Senegal. Som...,"{'type': 'text/html', 'language': None, 'base'...",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,"{'type': 'text/plain', 'language': None, 'base..."
10,"RW,advisory",False,http://travel.state.gov/content/travel/en/trav...,http://travel.state.gov/content/travel/en/trav...,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",<p>Exercise normal precautions in Rwanda. Some...,"{'type': 'text/html', 'language': None, 'base'...",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,"{'type': 'text/plain', 'language': None, 'base..."
100,"TP,advisory",False,http://travel.state.gov/content/travel/en/trav...,http://travel.state.gov/content/travel/en/trav...,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",<p>Exercise normal precautions in Sao Tome and...,"{'type': 'text/html', 'language': None, 'base'...",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,"{'type': 'text/plain', 'language': None, 'base..."
101,"AY,advisory",False,http://travel.state.gov/content/travel/en/trav...,http://travel.state.gov/content/travel/en/trav...,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",<p>Exercise increased caution in Antarctica du...,"{'type': 'text/html', 'language': None, 'base'...",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,"{'type': 'text/plain', 'language': None, 'base..."

### Dropping features and observations

In [7]:
column_to_drop = ['dc_identifier','guidislink','id','link','summary','summary_detail','title_detail']
dos_score = dos_score.drop(column_to_drop, axis=1)

In [8]:
dos_score.head()

,links,published,published_parsed,tags,title
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution

In [9]:
dos_score = dos_score.drop(107)

In [10]:
dos_score.reset_index()

,index,links,published,published_parsed,tags,title
0,0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions
1,1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions
2,10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions
3,100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...
4,101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution
5,102,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 02 Jan 2020","[2020, 1, 2, 0, 0, 0, 3, 2, 0]","[{'term': 'Level 3: Reconsider Travel', 'schem...",Democratic Republic of the Congo - Level 3: Re...
6,103,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 07 Nov 2019","[2019, 11, 7, 0, 0, 0, 3, 311, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Ecuador - Level 2: Exercise Increased Caution
7,104,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 27 Dec 2019","[2019, 12, 27, 0, 0, 0, 4, 361, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Indonesia - Level 2: Exercise Increased Caution
8,105,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Jul 2019","[2019, 7, 25, 0, 0, 0, 3, 206, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Latvia - Level 1: Exercise Normal Precautions
9,106,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 09 Apr 2019","[2019, 4, 9, 0, 0, 0, 1, 99, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Philippines - Level 2: Exercise Increased Caution
10,108,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 03 Mar 2020","[2020, 3, 3, 0, 0, 0, 1, 63, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Marshall Islands - Level 1: Exercise Normal Pr...
11,109,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 22 May 2019","[2019, 5, 22, 0, 0, 0, 2, 142, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Togo - Level 1: Exercise Normal Precautions
12,11,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 02 Aug 2019","[2019, 8, 2, 0, 0, 0, 4, 214, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Uruguay - Level 2: Exercise Increased Caution
13,110,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 09 Apr 2019","[2019, 4, 9, 0, 0, 0, 1, 99, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Uganda - Level 2: Exercise Increased Caution
14,111,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 27 Sep 2019","[2019, 9, 27, 0, 0, 0, 4, 270, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Finland - Level 1: Exercise Normal Precautions
15,112,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 14 Jan 2020","[2020, 1, 14, 0, 0, 0, 1, 14, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Croatia - Level 1: Exercise Normal Precautions
16,113,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 22 Apr 2019","[2019, 4, 22, 0, 0, 0, 0, 112, 0]",[{'term': 'Level 2: Exercise Increased Caution...,United Kingdom - Level 2: Exercise Increased C...
17,114,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 25 Feb 2019","[2019, 2, 25, 0, 0, 0, 0, 56, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Turks and Caicos Islands - Level 2: Exercise I...
18,115,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 26 Feb 2019","[2019, 2, 26, 0, 0, 0, 1, 57, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Montserrat - Level 1: Exercise Normal Precautions
19,116,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 03 Apr 2019","[2019, 4, 3, 0, 0, 0, 2, 93, 0]","[{'term': 'Level 3: Reconsider Travel', 'schem...",Nicaragua - Level 3: Reconsider Travel
20,117,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 07 Jan 2019","[2019, 1, 7, 0, 0, 0, 0, 7, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Cambodia - Level 1: Exercise Normal Precautions
21,118,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 25 Jun 2019","[2019, 6, 25, 0, 0, 0, 1, 176, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Bosnia and Herzegovina - Level 2: Exercise Inc...
22,119,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 15 Apr 2019","[2019, 4, 15, 0, 0, 0, 0, 105, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Dominican Republic - Level 2: Exercise Increas...
23,12,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 07 Mar 2019","[2019, 3, 7, 0, 0, 0, 3, 66, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Barbados - Level 1: Exercise Normal Precautions
24,120,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 21 Oct 2019","[2019, 10, 21, 0, 0, 0, 0, 294, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Spain - Level 2: Exercise Increased Caution
25,121,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 08 Oct 2019","[2019, 10, 8, 0, 0, 0, 1, 281, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Liechtenstein - Level 1: Exercise Normal Preca...
26,122,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 01 Nov 2019","[2019, 11, 1, 0, 0, 0, 4, 305, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Brunei - Level 1: Exercise Normal Precautions
27,123,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 13 Dec 2018","[2018, 12, 13, 0, 0, 0, 3, 347, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Uzbekistan - Level 1: Exercise Normal Precautions
28,124,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 09 Apr 2019","[2019, 4, 9, 0, 0, 0, 1, 99, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Kenya - Level 2: Exercise Increased Caution
29,125,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 15 Apr 2019","[2019, 4, 15, 0, 0, 0, 0, 105, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Saint Lucia - Level 1: Exercise Normal Precaut...
...,...,...,...,...,...,...
179,72,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 17 Jul 2019","[2019, 7, 17, 0, 0, 0, 2, 198, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Ghana - Level 1: Exercise Normal Precautions
180,73,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 08 Jan 2019","[2019, 1, 8, 0, 0, 0, 1, 8, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Aruba - Level 1: Exercise Normal Precautions
181,74,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 29 Mar 2019","[2019, 3, 29, 0, 0, 0, 4, 88, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sweden - Level 1: Exercise Normal Precautions
182,75,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 19 Nov 2019","[2019, 11, 19, 0, 0, 0, 1, 323, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,French Guiana - Level 1: Exercise Normal Preca...
183,76,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 07 May 2019","[2019, 5, 7, 0, 0, 0, 1, 127, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Saint Kitts and Nevis - Level 1: Exercise Norm...
184,77,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Gabon - Level 1: Exercise Normal Precautions
185,78,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 26 Feb 2020","[2020, 2, 26, 0, 0, 0, 2, 57, 0]","[{'term': 'Level 3: Reconsider Travel', 'schem...",Mongolia - Level 3: Reconsider Travel
186,79,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 01 Oct 2019","[2019, 10, 1, 0, 0, 0, 1, 274, 0]",[{'term': 'Level 2: Exercise Increased Caution...,El Salvador - Level 2: Exercise Increased Caution
187,8,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 06 Jan 2020","[2020, 1, 6, 0, 0, 0, 0, 6, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Bolivia - Level 2: Exercise Increased Caution
188,80,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 17 Jul 2019","[2019, 7, 17, 0, 0, 0, 2, 198, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Madagascar - Level 2: Exercise Increased Caution
189,81,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 14 Jan 2020","[2020, 1, 14, 0, 0, 0, 1, 14, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Poland - Level 1: Exercise Normal Precautions
190,82,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 18 Dec 2019","[2019, 12, 18, 0, 0, 0, 2, 352, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Mauritius - Level 1: Exercise Normal Precautions
191,83,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 17 Jul 2019","[2019, 7, 17, 0, 0, 0, 2, 198, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Moldova - Level 1: Exercise Normal Precautions
192,84,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 27 Dec 2019","[2019, 12, 27, 0, 0, 0, 4, 361, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Namibia - Level 1: Exercise Normal Precautions
193,85,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 29 Oct 2019","[2019, 10, 29, 0, 0, 0, 1, 302, 0]","[{'term': 'Level 3: Reconsider Travel', 'schem...",Nigeria - Level 3: Reconsider Travel
194,86,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 02 Jan 2019","[2019, 1, 2, 0, 0, 0, 2, 2, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Tunisia - Level 2: Exercise Increased Caution
195,87,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 02 May 2019","[2019, 5, 2, 0, 0, 0, 3, 122, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Maldives - Level 2: Exercise Increased Caution
196,88,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 05 Jul 2019","[2019, 7, 5, 0, 0, 0, 4, 186, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Greece - Level 1: Exercise Normal Precautions
197,89,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 12 Dec 2019","[2019, 12, 12, 0, 0, 0, 3, 346, 0]","[{'term': 'Level 4: Do Not Travel', 'scheme': ...",Central African Republic - Level 4: Do Not Travel
198,9,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 02 Jan 2019","[2019, 1, 2, 0, 0, 0, 2, 2, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Taiwan - Level 1: Exercise Normal Precautions
199,90,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 28 Oct 2019","[2019, 10, 28, 0, 0, 0, 0, 301, 0]","[{'term': 'Level 4: Do Not Travel', 'scheme': ...",Somalia - Level 4: Do Not Travel
200,91,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 25 Feb 2019","[2019, 2, 25, 0, 0, 0, 0, 56, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Grenada - Level 1: Exercise Normal Precautions
201,92,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 13 Sep 2019","[2019, 9, 13, 0, 0, 0, 4, 256, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Norway - Level 1: Exercise Normal Precautions
202,93,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 03 Dec 2019","[2019, 12, 3, 0, 0, 0, 1, 337, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Tanzania - Level 2: Exercise Increased Caution
203,94,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 07 Nov 2019","[2019, 11, 7, 0, 0, 0, 3, 311, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Tonga - Level 1: Exercise Normal Precautions
204,95,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 26 Nov 2019","[2019, 11, 26, 0, 0, 0, 1, 330, 0]","[{'term': 'Level 4: Do Not Travel', 'scheme': ...",South Sudan - Level 4: Do Not Travel
205,96,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 19 Feb 2020","[2020, 2, 19, 0, 0, 0, 2, 50, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Ukraine - Level 2: Exercise Increased Caution
206,97,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 04 Nov 2019","[2019, 11, 4, 0, 0, 0, 0, 308, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Ireland - Level 1: Exercise Normal Precautions
207,98,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Tue, 04 Feb 2020","[2020, 2, 4, 0, 0, 0, 1, 35, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Palau - Level 1: Exercise Normal Precautions
208,99,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Mon, 10 Feb 2020","[2020, 2, 10, 0, 0, 0, 0, 41, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Russia - Level 2: Exercise Increased Caution

### Cleaning the data (Source)

In [11]:
dos_score.links[0][0]['href']

'http://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/bhutan-travel-advisory.html'

In [12]:
dos_score['Source'] = [x[0]['href'] for x in dos_score.links]
dos_score.head()

,links,published,published_parsed,tags,title,Source
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...

### Cleaning the data (ISO)

In [13]:
dos_score.tags[0][1]['term']

'BT'

In [14]:
dos_score['ISO'] = [x[1]['term'] for x in dos_score.tags]
dos_score.head()

,links,published,published_parsed,tags,title,Source,ISO
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,BT
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,SG
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,RW
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...,TP
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...,AY

### Cleaning the data (Name)

In [15]:
import re

In [16]:
name = re.match(r'^.*?(?= -)', dos_score.title[0])
name.group()

'Bhutan'

In [17]:
def only_name(line):
    name = re.search(r'^.*?(?= -)', line)
    if name :
      return(name.group())

In [18]:
dos_score['Name'] = dos_score['title'].apply(only_name)
dos_score.head()

,links,published,published_parsed,tags,title,Source,ISO,Name
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,BT,Bhutan
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,SG,Senegal
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,RW,Rwanda
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...,TP,Sao Tome and Principe
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...,AY,Antarctica

### Cleaning the data (Score)

In [19]:
score = re.search(r'\d(?=:)',dos_score.title[0])
score.group()

'1'

In [20]:
def only_score(line):
    score = re.search(r'\d(?=:)', line)
    if score :
      return(score.group())

In [21]:
dos_score['Score'] = dos_score['title'].apply(only_score)
dos_score.head()

,links,published,published_parsed,tags,title,Source,ISO,Name,Score
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,BT,Bhutan,1
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,SG,Senegal,1
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,RW,Rwanda,1
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...,TP,Sao Tome and Principe,1
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...,AY,Antarctica,2

In [30]:
dos_score['Score'] = dos_score.Score.astype('float32')

In [31]:
dos_score.dtypes

links                object
published            object
published_parsed     object
tags                 object
title                object
Source               object
ISO                  object
Name                 object
Score               float32
dtype: object

In [32]:
dos_score.Score.add(.0)

0      1.0
1      1.0
10     1.0
100    1.0
101    2.0
102    3.0
103    2.0
104    2.0
105    1.0
106    2.0
108    1.0
109    1.0
11     2.0
110    2.0
111    1.0
112    1.0
113    2.0
114    2.0
115    1.0
116    3.0
117    1.0
118    2.0
119    2.0
12     1.0
120    2.0
121    1.0
122    1.0
123    1.0
124    2.0
125    1.0
      ...
72     1.0
73     1.0
74     1.0
75     1.0
76     1.0
77     1.0
78     3.0
79     2.0
8      2.0
80     2.0
81     1.0
82     1.0
83     1.0
84     1.0
85     3.0
86     2.0
87     2.0
88     1.0
89     4.0
9      1.0
90     4.0
91     1.0
92     1.0
93     2.0
94     1.0
95     4.0
96     2.0
97     1.0
98     1.0
99     2.0
Name: Score, Length: 209, dtype: float32

### Cleaning the data (Status)

In [33]:
dos_score.tags[0][0]['term']

'Level 1: Exercise Normal Precautions'

In [34]:
dos_score['Status'] = [x[0]['term'] for x in dos_score.tags]
dos_score.head()

,links,published,published_parsed,tags,title,Source,ISO,Name,Score,Status
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,BT,Bhutan,1.0,Level 1: Exercise Normal Precautions
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,SG,Senegal,1.0,Level 1: Exercise Normal Precautions
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,RW,Rwanda,1.0,Level 1: Exercise Normal Precautions
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...,TP,Sao Tome and Principe,1.0,Level 1: Exercise Normal Precautions
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...,AY,Antarctica,2.0,Level 2: Exercise Increased Caution

In [35]:
status = re.search(r'(?<=: ).*?$',dos_score['Status'][0])
status.group(0)

'Exercise Normal Precautions'

In [36]:
type(dos_score['Status'][0])

str

In [37]:
def only_status(line):
    stat = re.search(r'(?<=: ).*?$', line)
    return stat.group(0)

In [38]:
dos_score['Status'] = dos_score['Status'].apply(only_status)
dos_score.head()

,links,published,published_parsed,tags,title,Source,ISO,Name,Score,Status
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25, 0, 0, 0, 4, 25, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,BT,Bhutan,1.0,Exercise Normal Precautions
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,SG,Senegal,1.0,Exercise Normal Precautions
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,RW,Rwanda,1.0,Exercise Normal Precautions
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...,TP,Sao Tome and Principe,1.0,Exercise Normal Precautions
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...,AY,Antarctica,2.0,Exercise Increased Caution

### Cleaning the data (Last Update)

In [39]:
from datetime import date

In [40]:
s = dos_score.published_parsed[0]
del s[3:]
s

[2019, 1, 25]

In [41]:
if dos_score.published_parsed[0][1] < 10:
    print('0' + str(dos_score.published_parsed[0][1]))

01

In [42]:
if dos_score.published_parsed[0][2] < 10:
    print('0' + str(dos_score.published_parsed[0][2]))
else:
    print(str(dos_score.published_parsed[0][2]))

25

In [43]:
def date_transform(lista):
    nl = []
    nl.append(str(lista[0]))
    
    if lista[1] < 10:
        nl.append('0' + str(lista[1]))
    else:
        nl.append(str(lista[1]))
        
    if lista[2] < 10:
        nl.append('0' + str(lista[2]))
    else:
        nl.append(str(lista[2]))
        
    date_string = '-'.join([str(elem) for elem in nl])
    return date(*map(int, date_string.split('-')))

In [44]:
dos_score['Last Update'] = dos_score.published_parsed.apply(date_transform)
dos_score.head()

,links,published,published_parsed,tags,title,Source,ISO,Name,Score,Status,Last Update
0,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Fri, 25 Jan 2019","[2019, 1, 25]",[{'term': 'Level 1: Exercise Normal Precaution...,Bhutan - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,BT,Bhutan,1.0,Exercise Normal Precautions,2019-01-25
1,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 25 Apr 2019","[2019, 4, 25, 0, 0, 0, 3, 115, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Senegal - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,SG,Senegal,1.0,Exercise Normal Precautions,2019-04-25
10,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Wed, 11 Dec 2019","[2019, 12, 11, 0, 0, 0, 2, 345, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Rwanda - Level 1: Exercise Normal Precautions,http://travel.state.gov/content/travel/en/trav...,RW,Rwanda,1.0,Exercise Normal Precautions,2019-12-11
100,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 1: Exercise Normal Precaution...,Sao Tome and Principe - Level 1: Exercise Norm...,http://travel.state.gov/content/travel/en/trav...,TP,Sao Tome and Principe,1.0,Exercise Normal Precautions,2019-01-10
101,"[{'rel': 'alternate', 'type': 'text/html', 'hr...","Thu, 10 Jan 2019","[2019, 1, 10, 0, 0, 0, 3, 10, 0]",[{'term': 'Level 2: Exercise Increased Caution...,Antarctica - Level 2: Exercise Increased Caution,http://travel.state.gov/content/travel/en/trav...,AY,Antarctica,2.0,Exercise Increased Caution,2019-01-10

### Dropping unnecessary features

In [45]:
columns_to_drop = ['links','published','published_parsed', 'tags', 'title']
dos_score = dos_score.drop(columns_to_drop, axis=1)

In [46]:
dos_score.head()

,Source,ISO,Name,Score,Status,Last Update
0,http://travel.state.gov/content/travel/en/trav...,BT,Bhutan,1.0,Exercise Normal Precautions,2019-01-25
1,http://travel.state.gov/content/travel/en/trav...,SG,Senegal,1.0,Exercise Normal Precautions,2019-04-25
10,http://travel.state.gov/content/travel/en/trav...,RW,Rwanda,1.0,Exercise Normal Precautions,2019-12-11
100,http://travel.state.gov/content/travel/en/trav...,TP,Sao Tome and Principe,1.0,Exercise Normal Precautions,2019-01-10
101,http://travel.state.gov/content/travel/en/trav...,AY,Antarctica,2.0,Exercise Increased Caution,2019-01-10

In [47]:
column_order = ['Name','ISO','Score','Status','Last Update','Source']
dos_score = dos_score[column_order]

### Sort alphabetically

In [48]:
dos_score = dos_score.sort_values('Name')

In [49]:
dos_score = dos_score.reset_index(drop=True)

## III. Reporting

In [50]:
dos_score.to_csv('/Users/alejandroarrya/Desktop/Ironhack/DAPTMX/final_project/TASAM_final_project/data/dos_rss.csv')